# This Dockerfile aims to have at least one of everything, to exercise the
# comprehensiveness of Dockerfile feature support.
#
# See: https://docs.docker.com/engine/reference/builder
#
# ch-test-scope: standard

#FROM alpine
#FROM alpine@cdf98d1859c1  # skopeo pukes on this
FROM alpine:3.9
#FROM alpine:3.9 AS stage1

RUN apk add --no-cache bc
RUN ["echo", "hello \nworld"]

 # leading whitespace comment

# TODO:
# comment with trailing backslash (line continuation does not work in comments)
# escaped newlines are finding their way through to the commands
