FROM debian9

# OS packages needed to build OpenMPI.
RUN apt-get install -y \
    file \
    flex \
    g++ \
    gcc \
    gfortran \
    hwloc-nox \
    less \
    libdb5.3-dev \
    libfabric-dev \
    libhwloc-dev \
    libibverbs-dev \
    libnuma-dev \
    libpmi2-0-dev \
    libpsm-infinipath1-dev \
    make \
    wget

# Compile OpenMPI. We can't use the Debian package because we need a specific
# version and we need to build a little differently:
#
#   1. --disable-pty-support to avoid "pipe function call failed when
#      setting up I/O forwarding subsystem".
#
#   2. --with-slurm=no so mpirun in the container doesn't try use Slurm to
#       launch processes, which will fail in inscrutable ways e.g. if srun is
#       not found. (If you do want Slurm launching processes, use srun or
#       mpirun outside the container.)
#
ENV MPI_URL https://www.open-mpi.org/software/ompi/v2.1/downloads
ENV MPI_VERSION 2.1.2
WORKDIR /usr/src
RUN wget -nv ${MPI_URL}/openmpi-${MPI_VERSION}.tar.gz
RUN tar xf openmpi-${MPI_VERSION}.tar.gz
RUN    cd openmpi-${MPI_VERSION} \
    && CFLAGS=-O3 \
       CXXFLAGS=-O3 \
       ./configure --prefix=/usr \
                   --sysconfdir=/mnt/0 \
                   --disable-pty-support \
                   --with-pmi \
                   --with-pmi-libdir=/usr/lib/x86_64-linux-gnu \
                   --with-pmix \
                   --with-slurm=no \
    && make -j$(getconf _NPROCESSORS_ONLN) install
RUN rm -Rf openmpi-${MPI_VERSION}*

# Silence warnings about this directory not existing.
RUN mkdir /etc/libibverbs.d

# OpenMPI expects this program to exist, even if it's not used. Default is
# "ssh : rsh", but that's not installed.
RUN echo 'plm_rsh_agent = false' >> /mnt/0/openmpi-mca-params.conf
