# This Dockerfile is used to test that ch-tug deals with replacement of
# symlink with a regular file correctly (see issue #819).
#
# To build and push:
#
#   $ sudo docker login   # if needed
#   $ sudo docker build -t symlink -f Dockerfile.symlink .
#   $ sudo docker tag symlink:latest charliecloud/symlink
#   $ sudo docker images | fgrep symlink
#   $ sudo docker push charliecloud/symlink
#
# ch-test-scope: skip

FROM 00_tiny
WORKDIR /test

# Set up a symlink.
RUN echo target > target \
 && ln -s target source

# source and target should both contain "target".
RUN ls -l /test \
 && for i in /test/*; do printf '%s : ' $i; cat $i; done

# Overwrite it with a regular file.
RUN rm source \
 && echo regular > source

# Now source should be a regular file and contain "regular".
RUN ls -l /test \
 && for i in /test/*; do printf '%s : ' $i; cat $i; done

