# Test ARG and ENV handling.

# ch-test-scope: standard
FROM 00_tiny

ARG chse_arg1_df
ARG chse_arg2_df=arg2
ARG chse_arg3_df="arg3 ${chse_arg2_df}"
ENV chse_env1_df env1
ENV chse_env2_df="env2 ${chse_env1_df}"
RUN env | egrep '^chse_' | sort
