# Several images that fail to build without fakeroot injection.
#
# These images don't build on one another; they're a multi-stage only for
# organizational convenience.
#
# ch-test-scope: standard
# ch-test-builder-include: ch-image

# CentOS 7
FROM centos:7
RUN yum install -y openssh

# CentOS 8
FROM centos:8
RUN dnf install -y --setopt=install_weak_deps=false openssh

# Debian 9 (Stretch). Notes:
#
#   1. Tests list form of RUN.
#
#   2. fontconfig-config calls chown(1), which looks up users & groups by
#      name. This fails if the expected user or group is not present.
#
#   3. openssh-client calls chgrp(2).
#
FROM debian:stretch
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "fontconfig-config", "openssh-client"]

# Debian 10 (Buster)
# Note: Tests two apt-get in the same RUN. echo(1) should not get fakeroot.
FROM debian:buster
RUN echo hello
RUN apt-get update \
 && apt-get install -y fontconfig-config openssh-client
