# Minimal image useful for later tests.

# ch-test-scope: quick

FROM alpine:3.9

# For testing that permissions are retained on export (issue #1241). See FAQ
# for why these aren't 7777.
RUN touch /maxperms_file \
 && chmod 0777 /maxperms_file \
 && mkdir /maxperms_dir \
 && chmod 1777 /maxperms_dir
