# Minimal image useful for later tests.

# ch-test-scope: quick

FROM alpine:3.9

# For testing that permissions are retained on export (issue #1241). Setuid
# and setgid bits are stripped in various scenarios, so don't set them.
RUN touch /maxperms_file \
 && chmod 1777 /maxperms_file \
 && mkdir /maxperms_dir \
 && chmod 1777 /maxperms_dir
