#!/bin/bash

# grep(1) has options to support what we're doing with find(1), but I can't
# get them to work with rooted directories, e.g., test/bats vs bats anywhere
# in the tree. You may hear complaints about how find is too slow for this,
# but the project is small enough we don't care.

cd "$(dirname "$0")"/..

pwd
find . \(    -path ./.git \
          -o -path ./doc \
          -o -path ./doc-src/_build \
          -o -path ./man \
          -o -path ./test/bats \
       \) -prune \
       -o -type f \
       -exec grep --color=auto -Hn "$@" {} \;

#grep -r --exclude-dir=./test/bats "$@" .
