# -*- mode: ruby -*-
# vi: set ft=ruby :
##
# This file builds a VirtualBox Centos 7 guest OS environment with 
# Charliecloud, Docker, and OpenMPI.
##

# Require the proxy configurator plugin
if !Vagrant.has_plugin?("vagrant-proxyconf")
  raise("vagrant-proxyconf plugin is required; run 'vagrant plugin install vagrant-proxyconf'");
end

# Require the vagrant reload plugin
if !Vagrant.has_plugin?("vagrant-reload")
  raise("vagrant-reload plugin is required; run 'vagrant plugin install vagrant-reload'");
end

# Require persistent storage plugin
if !Vagrant.has_plugin?("vagrant-persistent-storage")
  raise("vagrant-reload plugin is required; run 'vagrant plugin install vagrant-persistent-storage'");
end

# Require etc module for processor count
require 'etc'

# Get proxy environment variables
unless ENV['http_proxy'].nil?
    proxy = ENV.fetch('http_proxy')
    url = '.' + URI.parse(proxy).host.downcase
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.require_version ">= 2.0.0"
Vagrant.configure("2") do |config|

    # Persistent Data Store
    config.persistent_storage.enabled = true
    config.persistent_storage.filesystem = 'btrfs'
    config.persistent_storage.location = '~/VirtualBox VMs/ch-storage/ch-disk.vdi'
    config.persistent_storage.mountname = 'LogVolData'
    config.persistent_storage.mountoptions = ['defaults', 'compress']
    config.persistent_storage.mountpoint = '/var/tmp/ch/'
    config.persistent_storage.partition = false
    config.persistent_storage.size = 87040  
    config.persistent_storage.volgroupname = 'VolGroupData'

    if proxy == ""
        config.git_proxy.http = ""
        config.proxy.ftp = ""
        config.proxy.http = ""
        config.proxy.https = ""
        config.proxy.no_proxy = ""
    else
        config.git_proxy.http = "#{proxy}"
        config.proxy.ftp = "#{proxy}"
        config.proxy.http = "#{proxy}"
        config.proxy.https = "#{proxy}"
        config.proxy.no_proxy = "localhost,127.0.0.1,#{url}"
    end 

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "centos/7"
    config.vm.hostname = "Charliecloud-VirtualBox"
    
    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    config.vm.box_check_update = false

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # NOTE: This will enable public access to the opened port
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine and only allow access
    # via 127.0.0.1 to disable public access
    config.vm.network "forwarded_port", guest: 20, host: 2020, host_ip: "127.0.0.1"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # config.vm.network "private_network", ip: "192.168.61.2"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # config.vm.network "public_network"
    
    config.vm.provider "virtualbox" do |vb|

        vb.name = "Charliecloud"
        vb.gui = false
        vb.memory = "4096"
        vb.cpus = Etc.nprocessors
    end

    # Install packages and configure namespaces    
    config.vm.provision "bootstrap", type: "shell", run: "always", privileged: true, inline: <<-SHELL
        yum makecache fast
        yum-config-manager --setopt=deltarpm=0 --save
        yum -y upgrade
        yum -y install git gcc gcc-c++ make binutils yum-utils device-mapper-persistent-data lvm2 screen wget curl
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum -y install docker-ce.x86_64
        systemctl enable docker && systemctl start docker

    echo 1885 > /proc/sys/user/max_user_namespaces
        echo "user.max_user_namespaces = 32767" > /etc/sysctl.d/51-userns.conf
        fgrep -q unpriv_enable /proc/cmdline \
            || grubby --args="user_namespace.enable=1 namespace.unpriv_enable=1 user.max_user_namespaces=32767" --update-kernel=ALL

    chmod 1777 /var/tmp/ch
    SHELL

    # Add groups and edit user permission
    config.vm.provision "groups", type: "shell", privileged: true, inline: <<-SHELL
        groupadd chtest
        usermod -aG chtest vagrant
        echo "vagrant ALL=(ALL:ALL) NOPASSWD:   ALL" >> /etc/sudoers
    SHELL

    # Enabe proxy settings for the docker systemd service file
    config.vm.provision "dockerproxy", type: "shell", privileged: true, inline: <<-SHELL
        rm -Rf /etc/systemd/system/docker.service.d
        mkdir /etc/systemd/system/docker.service.d/
        echo "[Service]" >> /etc/systemd/system/docker.service.d/http-proxy.conf
        echo "Environment=\"HTTP_PROXY=$http_proxy\"" >> /etc/systemd/system/docker.service.d/http-proxy.conf
        echo "Environment=\"HTTPS_PROXY=$http_proxy\"" >> /etc/systemd/system/docker.service.d/http-proxy.conf
        systemctl daemon-reload
        systemctl restart docker
    SHELL

    # Install OpenMPI (optionally) with 'vagrant up --provision-with openmpi'
    config.vm.provision "openmpi", type: "shell", privileged: true, run: "never", inline: <<-SHELL
        export VERSION=2.1.3
        cd /usr/local/src
        wget https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-${VERSION}.tar.gz
        tar xf openmpi-${VERSION}.tar.gz
        rm openmpi-${VERSION}.tar.gz
        cd openmpi-${VERSION}/
        ./configure --prefix=/usr/local/ --disable-mpi-cxx --disable-mpi-fortran
        make -j$(getconf _NPROCESSORS_ONLN)
        make install
        make clean
    SHELL

    config.vm.provision :reload

    # Install Charliecloud
    config.vm.provision "chmake", type: "shell", privileged: false, inline: <<-SHELL
        git clone --recursive https://github.com/hpc/charliecloud.git ~/charliecloud
        cd ~/charliecloud
        make && sudo make install PREFIX=/usr/local
    SHELL

    # Test Charliecloud (optional) with 'vagrant up --provision-with chtests'
     config.vm.provision "chtests", type: "shell", run: "never", privileged: false, 
        env: {"CH_TEST_TARDIR"=>"/var/tmp/ch/tarballs",
            "CH_TEST_IMGDIR"=>"/var/tmp/ch/images",
            "CH_TEST_PERMDIRS"=>"/var/tmp/ch",
            "CH_TEST_SCOPE"=>"full"}, 
        inline: <<-SHELL
        cd ~/charliecloud/test
        for d in $CH_TEST_PERMDIRS; do sudo ./make-perms-test $d $USER nobody; done
        make test-build && make test-run && make test-test
    SHELL
end
