# ch-test-scope: standard
# ch-test-arch-exclude: ppc64le  # base image unavailable
FROM debian:stretch

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
 && apt-get install -y --no-install-recommends apt-utils \
 && rm -rf /var/lib/apt/lists/*
