# ch-test-scope: standard
FROM debian:stretch

ARG DEBIAN_FRONTEND=noninteractive
RUN    apt-get update \
    && apt-get install --no-install-recommends -y apt-utils \
    && rm -rf /var/lib/apt/lists/*
