# ch-test-scope: full
FROM mpich

RUN dnf install -y which \
 && dnf clean all

# Compile the Intel MPI benchmark
WORKDIR /usr/local/src
ARG IMB_VERSION=IMB-v2021.3
RUN git clone --branch $IMB_VERSION --depth 1 \
              https://github.com/intel/mpi-benchmarks \
 && cd mpi-benchmarks/src_c \
 && make CC=mpicc -j$(getconf _NPROCESSORS_ONLN) -f Makefile TARGET=MPI1
