#!/bin/sh
export PATH=/opt/swift-t/stc/bin/:/opt/swift-t/turbine/bin:/usr/bin:/usr/local/openmpi/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export CUDA_VERSION=9.0.176
export CUDA_VERSION_WAR1936603=9.0.176_384.81
export CUDA_PKG_VERSION=9-0=9.0.176-1
export NCCL_VERSION=2.1.2
export NCCL_PKG_VERSION=2.1.2-1+cuda9.0
export CUBLAS_VERSION_WAR1936603=9.0.282_384.111
export CUBLAS_PKG_VERSION=9-0=9.0.282-1
export LD_LIBRARY_PATH=/usr/local/openmpi/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
export LIBRARY_PATH=/usr/local/cuda/lib64/stubs:
export CUDNN_VERSION=7.0.5
export CUDNN_VERSION_BUILD=7.0.5.15
export TENSORFLOW_VERSION=1.4.0+
export NVIDIA_TENSORFLOW_VERSION=18.02
export PYTHONIOENCODING=utf-8
export BAZELRC=/root/.bazelrc
export CUDA_TOOLKIT_PATH=/usr/local/cuda
export TF_CUDA_VERSION=9.0
export TF_CUDNN_VERSION=7
export CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
export TF_NEED_CUDA=1
export TF_CUDA_COMPUTE_CAPABILITIES=5.2,6.0,6.1,7.0
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_ENABLE_XLA=1
export CC_OPT_FLAGS=-march=sandybridge
export TF_ADJUST_HUE_FUSED=1
export TF_ADJUST_SATURATION_FUSED=1
export TF_ENABLE_WINOGRAD_NONFUSED=1
export TF_AUTOTUNE_THRESHOLD=2
export HOROVOD_GPU_ALLREDUCE=NCCL
export HOROVOD_NCCL_INCLUDE=/usr/include
export HOROVOD_NCCL_LIB=/usr/lib/x86_64-linux-gnu
export NVIDIA_BUILD_ID=337101
export BUILD_DIR=/opt
export TURBINE_PATH=/opt/swift-t/turbine
export TURBINE_LAUNCH_OPTIONS=--allow-run-as-root
export PATH=$PATH:/usr/local/openmpi/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export CUDA_VERSION=9.0.176
export CUDA_VERSION_WAR1936603=9.0.176_384.81
export CUDA_PKG_VERSION=9-0=9.0.176-1
export NCCL_VERSION=2.1.2
export NCCL_PKG_VERSION=2.1.2-1+cuda9.0
export CUBLAS_VERSION_WAR1936603=9.0.282_384.111
export CUBLAS_PKG_VERSION=9-0=9.0.282-1
export LD_LIBRARY_PATH=/usr/local/openmpi/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
export LIBRARY_PATH=/usr/local/cuda/lib64/stubs:
export CUDNN_VERSION=7.0.5
export CUDNN_VERSION_BUILD=7.0.5.15
export TENSORFLOW_VERSION=1.4.0+
export NVIDIA_TENSORFLOW_VERSION=18.02
export PYTHONIOENCODING=utf-8
export BAZELRC=/root/.bazelrc
export CUDA_TOOLKIT_PATH=/usr/local/cuda
export TF_CUDA_VERSION=9.0
export TF_CUDNN_VERSION=7
export CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
export TF_NEED_CUDA=1
export TF_CUDA_COMPUTE_CAPABILITIES=5.2,6.0,6.1,7.0
export TF_NEED_GCP=0
export TF_NEED_HDFS=0
export TF_ENABLE_XLA=1
export CC_OPT_FLAGS=-march=sandybridge
export TF_ADJUST_HUE_FUSED=1
export TF_ADJUST_SATURATION_FUSED=1
export TF_ENABLE_WINOGRAD_NONFUSED=1
export TF_AUTOTUNE_THRESHOLD=2
export HOROVOD_GPU_ALLREDUCE=NCCL
export HOROVOD_NCCL_INCLUDE=/usr/include
export HOROVOD_NCCL_LIB=/usr/lib/x86_64-linux-gnu
export NVIDIA_BUILD_ID=337101
