# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cri.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcri.proto\"\x10\n\x0eVersionRequest\"\"\n\x0fVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t26\n\x03\x43RI\x12/\n\nGetVersion\x12\x0f.VersionRequest\x1a\x10.VersionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cri_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERSIONREQUEST']._serialized_start=13
  _globals['_VERSIONREQUEST']._serialized_end=29
  _globals['_VERSIONRESPONSE']._serialized_start=31
  _globals['_VERSIONRESPONSE']._serialized_end=65
  _globals['_CRI']._serialized_start=67
  _globals['_CRI']._serialized_end=121
# @@protoc_insertion_point(module_scope)
